### ISSUE TITLE
[OMP Upgrade] Settings Management anpassen

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/urn_dnb#1]
Da der Alec jetzt das Setting Problem gefunden hast,  könntest Du schauen, ob es jetz  bei der DNB URN plugin  liegt oder ob Alec noch fixen muss.
doi plugin scheint zu laden.

**Comment by kadowa** [comment]
Bin schon dabei; Settings sind da, aber das Formular muss noch entsprechend zum DOI-Plugin angepasst werden.

**Comment by kadowa** [comment]
Depends on response to https://github.com/UB-Heidelberg/omp/issues/25.
